config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "how-to", to: "pages#how_to"
  get "profile", to: "pages#profile"
  
  # Custom route for generating outline text via LLM agent, calling method separate from the Task controller
  put "outline_generate", to: "outlines#generate"
  
  resources :tasks do
    member do
      get :download_outline
    end
    resources :outlines, only: [:create, :edit, :update, :destroy]
    resources :notes, only: [:create, :edit, :update, :destroy]
  end

  # get "tasks", to: "tasks#index"
  # get "tasks/:id", to: "tasks#show"
  # get "tasks/:id/edit", to: "tasks#edit"
  # post "tasks/:id/edit", to: "tasks#update"

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_one :outline, dependent: :destroy
  has_many :notes, dependent: :destroy

  # Allo nested attributes for notes
  accepts_nested_attributes_for :notes, allow_destroy: true
  accepts_nested_attributes_for :outline, allow_destroy: true

  # Mandates that at least a title and gen. prompt text must exist
  validates :title, presence: true
  validates :synopsis, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :download_outline]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
    @task
    @note = Note.new
  end

  def new
    @task = Task.new
    # Allow adding a Note in the simple_form, not requiring a separate form
    @task.notes.build # Prepare one Note model field in the #new form
    @task.build_outline
  end

  def create
    @task = current_user.tasks.new(task_params)
    # Assign an empty string to the Outline record contents. This makes view handling & record checking easier,
    # plus we'll always need the field anyhow. Otherwise, the child outline record would be NIL until saved with :contents
    # containing some value (non-empty field)
    @task.outline.contents = ""

    if @task.save!
      redirect_to task_path(@task), notice: "✔ Task created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task
    @note = Note.new
    @outline = Outline.new
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render edit_task_path(@task), notice: "✖ Task edit failed"
    end
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  def download_outline

    format_type = params[:format_type]
    text_contents = clean_markdown_contents(@task.outline.contents)

    if format_type == 'txt'
      send_data text_contents,
      filename: "#{@task.title.parameterize}.txt",
      type: "text/plain",
      disposition: "attachment"
    elsif format_type == 'pdf'
      pdf_file = generate_pdf(@task.title, text_contents)
      send_data pdf_file,
      filename: "#{@task.title.parameterize}.pdf",
      type: "application/pdf",
      disposition: "attachment"             
    end
  end 

  def generate_pdf(title, text)
    # Support PDF generation
    require "prawn"

    Prawn::Document.new do |pdf|
      pdf.text "Writing task outline", size: 20, style: :bold
      pdf.text "Title: #{title}", size: 20, style: :bold
      pdf.move_down 10
      pdf.text text, size: 16
    end.render
  end

  def clean_markdown_contents(text)
    # Removes Markdown '#' characters before a download - should not be needed for typical outpline
    # format generated by AI agent for the user. Uses regex express for 1+ '#' chars. followed by a whitespace
    # Also removes one or more asterisks (Markdown for bold, italics)
    cleaned = text.gsub(/\#+\s/, '')
    cleaned.gsub(/\*+/, '')
  end
  
  # #####################################################
  
  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :title, :synopsis,
      notes_attributes: [:id, :text],
      outline_attributes: [:id, :contents]
    )
  end

end

app/views/tasks/_task.html.erb
<div class="card col-5 m-1" id="<%= dom_id(task) %>">

    <div class="card-body">
        <!-- show task title & indicate if an associated outline exists -->
        <div class="mb-2">
            <h4 class="card-title d-flex align-center"><%= task.title %></h4>
            <%= raw('<span class="badge bg-success text-light"><i class="fa-solid fa-check"></i> Outline</span>') if !task.outline.contents.empty? %>
            <span class="badge bg-primary">ID: <%= task.id %></span>
        </div>
        <p class="mb-0"><strong>Assignment notes:</strong>
        
        <% if task.notes.present? %>
            <%= "#{task.notes.count} saved" %>
        <% else %>
            <p><em>(No notes yet)</em></p>
        <% end %>
        </p>
        <p class="mb-1"><strong>Synopsis:</strong></p>
        <p class="text-muted fst-italic"><%= truncate(task.synopsis, length: 90) %></p>
        <hr>
        <span class="d-flex justify-content-between">
            <span>
                <%= link_to raw('<i class="fa-regular fa-eye"></i> Details'), task_path(task.id), class: "text-decoration-none me-2" %>
                <%= link_to raw('<i class="fa-solid fa-pencil"></i> Edit task'), edit_task_path(task.id), 
                    class: "text-decoration-none" 
                %>
            </span>
            <%= link_to raw('<i class="fa-regular fa-trash-can"></i> Delete'), task_path(task), data: {turbo_method: :delete, turbo_confirm: "Delete tasK?"},
                class: "text-decoration-none" %>
        </span>
    </div>

</div>

app/views/tasks/edit.html.erb
<div class="container">
    
    <div class="col-10 bg-white rounded-3 mt-3 p-3">
        <h1 class="mt-3">Edit writing task</h1>
        <p class="fst-italic text-black-50"><small>* indicates the field cannot be blank.</small></p>
        <%= simple_form_for @task do |t| %>
            <%= t.input :title, label_html: { class: "fw-bold"} %>
            <%= t.input :synopsis, label_html: { class: "fw-bold"} %>

            <!-- Use attributes to add note (optional) in the same form -->
            <% if @task.outline.present? %>
                <%= t.fields_for :outline do |o| %>
                    <%= o.input :contents, as: :text, label: "Outline", label_html: { class: "fw-bold"},
                    input_html: { rows: 20, style: "white-space: pre-wrap;" } %>
                <% end %>
            <% end %>

            <% index = 0 %>
            <%= t.fields_for :notes do |note| %>
                <%= note.input :text, label: "Note ##{index += 1}", label_html: { class: "fw-bold"} %>
            <% end %>

            <%= t.submit "Update task", class: "btn btn-primary mb-2" %>
        <% end %>

        <% if !@task.outline.present? %>
            <%= simple_form_for [@task, @outline] do |outline| %>
                <%= outline.input :contents, as: :text, label: "Outline", label_html: { class: "fw-bold" } %>
                <%= outline.submit "Add outline", class: "btn btn-sm btn-success text-white rounded-3" %>
            <% end %>
        <% end %>

        <div class="mt-3">            
            <%= link_to raw('<i class="fa-solid fa-arrow-left"></i> All tasks'), tasks_path, 
                class: "text-decoration-none" 
            %>
        </div>   
    </div>
</div>

app/views/tasks/index.html.erb
<!-- "How to" page view, explaining basic use instructions to users (no login required) -->
<div class="container">

    <div class="bg-white rounded-3 mt-3 p-3">
        <div class="d-flex justify-content-between align-items-center">
            <%# Show the current count for user's tasks that exist %>
                <h1>My writing tasks (<%= @tasks.count %>)</h1>

                <a type="button" href="<%= url_for(new_task_path) %>" class="btn btn-primary btn-lg"><i class="fa-solid fa-plus"> </i>Add new task</a>

        </div>

        <%# Iterate over tasks already created and display as cards to user %>
        <div class="row row-cols-1 row-cols-md-2 g-3 mt-3">
            
            <% @tasks.each do |task| %>

            <div class="col">
                <!-- show task title & indicate if an associated outline exists -->
                <div class="row border p-2 m-1 bg-light" >

                    <h4 style="min-height: 60px;"><%= task.title %></h4>

                    <div class="mb-0">
                        <% if task.outline.contents.empty? %>
                            <%= raw('<span class="badge bg-danger-subtle"><i class="fa-solid fa-x"></i> No outline</span>') %>
                        <% else %>
                            <%= raw('<span class="badge bg-success text-light"><i class="fa-solid fa-check"></i> Outline</span>') %>
                        <!-- <% if Rails.env.development? %>
                            <span class="badge bg-primary">ID: <%= task.id %></span>
                        <% end %>
                        -->
                        <% end %>
                    </div>

                    <p class="mb-0"><strong>Assignment notes:</strong>
                    <% if task.notes.present? %>
                        <%= "#{task.notes.count} saved" %>
                    <% else %>
                        <em>(No notes yet)</em>
                    <% end %>
                    </p>
                    <p class="mb-0"><strong>Synopsis:</strong></p>
                    <p class="text-muted fst-italic mb-1" style="min-height: 60px;"><%= truncate(task.synopsis, length: 90) %></p>


                    <div class="row border-top border-2 m-1 p-0 pt-2">
                        <div class="col-6 col-lg-4">
                            <%= link_to raw('<i class="fa-regular fa-eye fa-sm"></i> Details'), task_path(task.id), class: "text-decoration-none" %>
                        </div>
                        <div class="col-6 col-lg-4">
                            <%= link_to raw('<i class="fa-solid fa-pencil fa-sm"></i> Edit task'), edit_task_path(task.id), 
                                class: "text-decoration-none" 
                            %>
                        </div>
                        <div class="col-12 col-lg-4">
                        <%= link_to raw('<i class="fa-regular fa-trash-can fa-sm"></i> Delete'), task_path(task), data: {turbo_method: :delete, turbo_confirm: "Delete tasK?"},
                            class: "text-decoration-none" %>
                        </div>
                    </div>

                </div>

            </div>
            <% end %>
        </div>
    </div>

</div>

app/views/tasks/new.html.erb
<div class="container">
    
    <div class="col-10 bg-white rounded-3 mt-3 p-3">
        <h1 class="mt-3">Create a new writing task</h1>
        <%  
            synopsis_string = "Create an outline summarizing the book into 10 main sections along with subsections for main characters..."
            note_string = 'A brief note like "Eng. comp 101, assignment #2"'
            title_string = 'Ex. "Essay summary for Moby Dick"'
        %>

        <%= simple_form_for @task do |t| %>
            <%= t.input :title, placeholder: title_string %>
            <%= t.input :synopsis, placeholder: synopsis_string %>
            <!-- Use attributes to add note (optional) in the same form -->

            <%= t.fields_for :outline do |outline| %>
                <%= outline.input :contents, label: "Outline" %>         
            <% end %>       

            <%= t.fields_for :notes do |note| %>
                <%= note.input :text, label: "Note (optional)",
                    placeholder: note_string, input_html: { maxLength: 400, height: 400 } 
                %>
            <% end %>

            <%= t.submit "Create task", class: "btn btn-primary mb-2" %>
        <% end %>
        <div>            
            <%= link_to raw('<i class="fa-solid fa-arrow-left"></i> All tasks'), tasks_path, 
                class: "text-decoration-none" 
            %>
        </div>        
    </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
    
    <div class="col-12 col-md-10  bg-white rounded-3 mt-3 p-3">
        <h1 class="mt-3">Writing task details</h1>
        <hr>
        <h3>Title:</h3>
            <% if Rails.env.development?  %>
                <h4 class="mb-3"><%= @task.title %></h4>
            <% else %>
                <h4 class="mb-3"><%= @task.title %></h4>
            <% end %>
        <h3>Synopsis:</h3>
        <p class="mb-3 bg-primary text-light p-3 rounded-3"><%= @task.synopsis %></p>
        <h3>Outline:</h3>
  
        <div class="mb-3 p-0 position-relative" id="div-outline">
            <!-- A new/empty outline is created by saving an empty string: "" -->
            <% if !@task.outline.contents.empty? %>
                <% text = @task.outline.contents %>
                <%= markdown(text) %>
                
                <span class="d-flex justify-content-end">
                    <%= link_to raw('<i class="fa-regular fa-trash-can"></i> Delete'), task_outline_path(@task, @task.outline), 
                        data: {turbo_method: :delete, turbo_confirm: "Delete outline?"},
                        class: "btn btn-sm btn-delete btn-outline-dark rounded-3 m-2"
                    %>
                </span>
                <!-- Adds file download buttons for send_data helper in Tasks controller -->
                <span class="d-flex justify-content-start">
                    <%= link_to raw('Download TXT file <i class="fa-solid fa-download"></i>'), 
                        download_outline_task_path(@task, format_type: 'txt'), 
                        class: "btn btn-success text-white rounded-3 m-2" %>
                    <%= link_to raw('Download PDF file <i class="fa-solid fa-download"></i>'), 
                        download_outline_task_path(@task, format_type: 'pdf'), 
                        class: "btn btn-success text-white rounded-3 m-2" %>
                </span>                
            <% else %>
                <!-- Insert an empty object to fill the empty outline field with whitespace -->
                <% outline_id = @task.outline.id %>
                <%= button_to raw('<i class="fa-solid fa-file-signature"></i> Generate outline'), 
                    outline_generate_path(id: outline_id, task_id: @task.id), method: :put,
                    class: "btn btn-success rounded-3", id: "btn-generate"
                %>
            <% end %>

        </div>
        <h3>Notes:</h3>
            <% if @task.notes.present? %>
                <% @task.notes.each do |note| %>
                    <p class="mb-3 bg-secondary text-dark fst-italic p-2 rounded-3 position-relative">
                        
                        <%= note.text %>
                        <br>
                        <%= link_to raw('<i class="fa-regular fa-trash-can"></i> Delete'), task_note_path(@task, note), 
                            data: {turbo_method: :delete, turbo_confirm: "Delete note?"},
                            class: "btn btn-sm btn-delete btn-outline-dark rounded-3 position-absolute bottom-0 end-0 m-2"
                        %>
                        <br>            
                    </p>                    
                <% end %>


            <% else %>
                <p class="fst-italic">(No notes addded yet)</p>
            <% end %>
        <hr>
        
        <%= simple_form_for [@task, @note] do |note| %>
            <%= note.input :text, label: "Add a note:", label_html: { class: "fw-bold"} %>
            <%= note.submit "Add note", class: "btn btn-sm btn-success text-white rounded-3" %>
        <% end %>

        <div class="d-flex justify-content-between mt-3">
            <%= link_to raw('<i class="fa-solid fa-arrow-left"></i> All tasks'), tasks_path, 
                class: "text-decoration-none" 
            %>
            <%= link_to raw('<i class="fa-solid fa-pencil"></i> Edit task'), edit_task_path(@task), 
                class: "text-decoration-none" 
            %>      
        </div>        
    </div>

</div>